### ISSUE TITLE
weird log when testing s3 using S3-CLI

### ISSUE THREAD

**Issue by mengwanguc** [Seagate/cortx-s3server#1078]
I was following S3 QSG. Everything went well. I successfully passed unit and system tests.  And I successfully tested my build using S3-CLI(Awesome!)

However, when I was testing my build using S3-CLI, I suddenly got this output from my terminal:

```
[root@s3 cortx-s3server]# E0803 18:19:35.027356 22243 s3_auth_client.cc:437] [handle_response] [ReqID: 8a7c186c-2546-4ca4-8ea1-b48828f985a7] Authentication failed

E0803 18:19:35.027542 22243 s3_auth_client.cc:1154] [on_common_failed] [ReqID: 8a7c186c-2546-4ca4-8ea1-b48828f985a7] Auth/validation failure

E0803 18:19:35.027567 22243 action_base.cc:294] [check_authentication_failed] [ReqID: 8a7c186c-2546-4ca4-8ea1-b48828f985a7] Authentication failure: InvalidAccessKeyId
```

I didn't run any command for a while. And these output just suddenly jump to my terminal.
I'm feeling it's a log from the s3 server .

It didn't cause any problem though. I can still successfully test all the commands using S3-CLI.

Not sure if it's a big issue but want to let you guys know.

**Comment by mengwanguc** [comment]
FYI, this happened again when I'm writing this github issue.

Before writing this github issue, I ran "cat ~/.aws/credentials" but at that time I didn't see these weird output.
```

[root@s3 cortx-s3server]# cat ~/.aws/credentials
[default]
aws_access_key_id = AKIAkSfDH3iFQDm5kihAZsiO3A
aws_secret_access_key = VjTPwj/5BU0NboEG1cCG7ZJNEokhlERh70mvyEyD
[root@s3 cortx-s3server]# E0803 18:40:00.986902 22243 s3_auth_client.cc:437] [handle_response] [ReqID: 4e0d2ae3-55a9-41d4-97d9-7617ce9a5032] Authentication failed

E0803 18:40:00.987129 22243 s3_auth_client.cc:1154] [on_common_failed] [ReqID: 4e0d2ae3-55a9-41d4-97d9-7617ce9a5032] Auth/validation failure

E0803 18:40:00.987156 22243 action_base.cc:294] [check_authentication_failed] [ReqID: 4e0d2ae3-55a9-41d4-97d9-7617ce9a5032] Authentication failure: InvalidAccessKeyId
```

**Comment by nileshgovande** [comment]
Thanks @mengwanguc
This is developer environment @mengwanguc  -  Hence when we launch s3server (and motr underneath) and demonize it, its WARNING/ERROR messages are logged in to the same shell from where it is launched (and it is intentional).

If you don't want to see these messages, the simplest way is to start a new terminal session and these messages will not appear.

**Comment by mengwanguc** [comment]
Thanks @nileshgovande , yes I'm also feeling it's a logging from s3 server (probably a periodic check).

I just want to make sure these logs are not harmful. 
Because I did follow QSG step by step but still saw these warnings like "Authentication failure: InvalidAccessKeyId", which makes me unsure if it's a big problem.
I was using non-SSL mode though.

I will close this issue if you confirm that these "Authentication failed" logging are not harmful.

**Comment by nileshgovande** [comment]
'Authentication failure: InvalidAccessKeyId' is not a big problem
It will come if there is an error in the access/secret key provided.
In fact, our STs themselves do this negative testing - so be rest assured.
@mengwanguc

**Comment by mengwanguc** [comment]
Got it thanks

**Comment by cortx-admin** [comment]
> Sachitanand Shelake commented in Jira Server:

No changes required

**Comment by cortx-admin** [comment]
> Sachitanand Shelake commented in Jira Server:

no work

**Comment by cortx-admin** [comment]
> Sachitanand Shelake commented in Jira Server:

no work required
