### ISSUE TITLE
cortx-s3server [Errno 14] HTTPS Error 403 - Forbidden

### ISSUE THREAD

**Issue by AmberJH** [Seagate/cortx-s3server#159]
After removed cortx-s3server folder, retried the procedures inside Cortx-S3Server QuickStart guide(https://github.com/Seagate/cortx/blob/main/doc/CortxS3ServerQuickStart.md).
Encountered error msg when $ **yum repolist** under Prerequisites:
=================================================================================
[root@ssc-vm-0963 cortx-s3server]# yum repolist
Loaded plugins: enabled_repos_upload, package_upload, priorities, product-id,
              : search-disabled-repos, subscription-manager
https://cdn.redhat.com/EOS/Production/RHEL-7-Server/custom/EPEL-7/EPEL-7/repoda                                               ta/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with R                                               ed Hat Support.

https://cdn.redhat.com/EOS/Production/RHEL-7-Server/custom/EPEL-7/EPEL-7/repoda                                               ta/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
https://cdn.redhat.com/EOS/Production/RHEL-7-Server/custom/Puppet6/puppet6-el7/                                               repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
Unable to upload Enabled Repositories Report
================================================================================
Following cannot run $ ./init.sh successfully under Installing dependency, msg as below:                                                                yum-config-manager --save --setopt=EOS_EPEL-7_EPEL-7.skip_if_unavai                                               lable=true

failure: repodata/repomd.xml from EOS_EPEL-7_EPEL-7: [Errno 256] No more mirror                                               s to try.
https://cdn.redhat.com/EOS/Production/RHEL-7-Server/custom/EPEL-7/EPEL-7/repoda                                               ta/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Uploading Enabled Repositories Report

**Comment by nileshgovande** [comment]
No response from @AmberJH in several days - closing stale issue
