### ISSUE TITLE
https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md suggestions

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-s3server#213]
![image](https://user-images.githubusercontent.com/68423216/93661312-59aa0680-fa89-11ea-8a47-cf9299b612b7.png)

![image](https://user-images.githubusercontent.com/68423216/93661513-f28d5180-fa8a-11ea-9218-d020355c2476.png)
![image](https://user-images.githubusercontent.com/68423216/93661521-fcaf5000-fa8a-11ea-95fe-c054ec659177.png)

**To install pip3 use: $ `yum install python3-pip`**

![image](https://user-images.githubusercontent.com/68423216/93661577-6a5b7c00-fa8b-11ea-9d37-c73dd6601b5a.png)

1,2,3 overlap with 1.0 Prerequisites
2 and 3 instructions are wrong

**Comment by johnbent** [comment]
@Saumya-Sunder , can you please address these if they still need to be addressed and then close this Issue after adding a comment with a link to the PR where you fix it?

**Comment by Saumya-Sunder** [comment]
Resolved in PR https://github.com/Seagate/cortx-s3server/pull/349
