### ISSUE TITLE
s3iamcli error 

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-s3server#214]
https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#14-test-your-build-using-s3-cli

Generate the AWS Access Key ID and Secret Key:
To check for help messages, use: $ s3iamcli -h
To create a new User, run: $ s3iamcli CreateAccount -n <Account Name> -e <Email Id>

> [root@ssc-vm-1091 cortx-s3server]# s3iamcli -h
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (botocore 1.18.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('botocore<1.18.0,>=1.17.62'), {'boto3'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/s3iamcli", line 4, in <module>
>     __import__('pkg_resources').run_script('s3iamcli==1.0.0', 's3iamcli')
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
>     @_call_aside
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (botocore 1.18.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('botocore<1.18.0,>=1.17.62'), {'boto3'})
> [root@ssc-vm-1091 cortx-s3server]# cd rpms
> [root@ssc-vm-1091 rpms]# ls
> bazel             gtest           log4cxx  python3x  s3certs  s3iamcli
> git-clang-format  haproxy-statsd  ossperf  s3        s3cmd
> [root@ssc-vm-1091 rpms]# s3iamcli -h
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (botocore 1.18.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('botocore<1.18.0,>=1.17.62'), {'boto3'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/s3iamcli", line 4, in <module>
>     __import__('pkg_resources').run_script('s3iamcli==1.0.0', 's3iamcli')
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
>     @_call_aside
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (botocore 1.18.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('botocore<1.18.0,>=1.17.62'), {'boto3'})
> [root@ssc-vm-1091 rpms]# ./s3iamcli -h
> -bash: ./s3iamcli: Is a directory
> [root@ssc-vm-1091 rpms]# s3iamcli
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (botocore 1.18.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('botocore<1.18.0,>=1.17.62'), {'boto3'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/s3iamcli", line 4, in <module>
>     __import__('pkg_resources').run_script('s3iamcli==1.0.0', 's3iamcli')
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
>     @_call_aside
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (botocore 1.18.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('botocore<1.18.0,>=1.17.62'), {'boto3'})
> [root@ssc-vm-1091 rpms]# ls
> bazel             gtest           log4cxx  python3x  s3certs  s3iamcli
> git-clang-format  haproxy-statsd  ossperf  s3        s3cmd
> [root@ssc-vm-1091 rpms]# cd s3iamcli
> [root@ssc-vm-1091 s3iamcli]# ls
> buildrpm.sh  s3iamcli.spec

**Comment by bkirunge7** [comment]
@yanqingfu  is this resolved, can we close this issue

**Comment by yanqingfu** [comment]
@bkirunge7 latest branch don't have this issue
