### ISSUE TITLE
Supported S3 API calls

### ISSUE THREAD

**Issue by msconsults** [Seagate/cortx-s3server#269]
Hello together,

I'm working a lot of times with AWS and I'm searching for the supported S3 API list of cortx to check if it's fit for my on-prem workloads.
Can you provide it, please?

Thanks and best regards, Marc

**Comment by johnbent** [comment]
Excellent @msconsults , thanks for your interest!  I transferred this into our main S3 module where either @nileshgovande can help answer or he can help identify the right person to get you the info you're looking for.  Welcome to CORTX!
