### ISSUE TITLE
Wasabi s3-benchmark fails with NotImplemented

### ISSUE THREAD

**Issue by ttwalkertt** [Seagate/cortx-s3server#270]
Hello-

The Wasabi s3-benchmark tool (https://github.com/wasabi-tech/s3-benchmark) causes S3 to return a NotImplemented error.

> 2020/08/11 23:37:16 FATAL: Unable to delete objects from bucket: ListObjectVersions unexpected failure: NotImplemented: A header you provided implies functionality that is not implemented.
>         status code: 501, request id: 8cfc1375-3b3e-4d43-8974-6b0093dbe24d, host id:

Do we implement **ListObjectVersions** ?

Note: /var/log/seagate/s3/s3server-0x7200000000000001:0x16/s3server.INFO contains similar info.

Thanks.

**Comment by johnbent** [comment]
@bkirunge7 , this is also related to https://github.com/Seagate/cortx-s3server/discussions/269.

**Comment by bkirunge7** [comment]
@ttwalkertt we don't support List object version. 

Please find below the list of S3 and IAM api's


S3 API | Short description
-- | --
PUT Bucket | Create a bucket with a specified name
PUT Object | Create an object in the bucket specified
INITIATE Multipart Upload | Initiates a multipart upload for the Put object operation
UPLOAD Part | Uploads individual parts of the object
COMPLETE Multipart Upload | Signals completion of multipart upload
ABORT Multipart Upload | Aborts the multipart upload in process
DELETE Bucket | Deletes the specified bucket
DELETE Object | Deletes the specified object
DELETE Multiple Objects | Deletes multiple objects from a bucket using a single HTTP request
DELETE Bucket policy | Deletes the Bucket Policy
GET Bucket ACL | Get the Bucket's Access Control List
GET Bucket policy | Get the Bucket Policy
GET Object ACL | Get the Object's Access Control List
List Multipart Uploads | List the multipart uploads in process
List Parts | List the parts of a multipart upload
HEAD Object | Get metadata of the object
GET Object | Download the object
GET Service | Get a list of all buckets owned by the requestor
GET Bucket (List Objects) | List objects in the bucket
Head Bucket | Get metadata of the bucket
PUT Bucket ACL | Apply a Bucket ACL
PUT Bucket policy | Apply a Bucket Policy
PUT Object ACL | Apply ACL to the specified object
GET Bucket Tagging | Uses the tagging sub-resource to return the tag set associated with the bucket.
Put Bucket Tagging | Uses the tagging sub-resource to add a set of tags to an existing bucket.
Delete Bucket Tagging | Uses the tagging sub-resource to remove a tag set from the specified bucket.

IAM Operations


IAM APIs | Description
-- | --
CreateAccount | Create an S3 account. This returns the Access Key, Secret Key.
ListAccounts | List existing accounts
DeleteAccount | Delete an account. This requires an account's access key, secret key
CreateUser | Creates a new IAM user for your AWS account
ListUsers | Lists the IAM users in the S3 account
UpdateUser | Updates the name and/or the path of the specified IAM user
CreateAccessKey | Creates a new AWS secret access key and corresponding AWS access key ID for the specified user
UpdateAccessKey | Updates the access key details like status, access key
ListAccessKeys | Returns information about the access key IDs associated with the specified IAM user
DeleteAccesskey | Deletes the access key pair associated with the specified IAM user


@amitwac2608  can you please help to add this to a doc and checkin to repo

**Comment by bkirunge7** [comment]
@ttwalkertt do you have any further queries, can we close this issue?

**Comment by ttwalkertt** [comment]
No further queries. Thanks.

Tim Walker
Product Design Systems Engineering, Seagate Technology
(303) 775-3770

________________________________
