### ISSUE TITLE
API Compatibility Guide needs to be linked

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-s3server#331]
The API Compatibility guide is not currently linked from any other files.  It should be.

**Comment by johnbent** [comment]
https://github.com/Seagate/cortx-s3server/blob/main/s3-supported-api.md

**Comment by Saumya-Sunder** [comment]
Done here @johnbent https://github.com/Seagate/cortx/pull/418. My PR for [S3API tables](https://github.com/Seagate/cortx-s3server/pull/325) still needs to be approved.

**Comment by nileshgovande** [comment]
Merged
