### ISSUE TITLE
Unable to disable selinux

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-s3server#334]
I'm running a CentOs 7 VM on AWS, and the [guide](https://github.com/Seagate/cortx-s3server/blob/dev/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md) to disable selinux doesn't work.

### Fix
Instead of

> sed 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

The following command was used instead
> sed **-i** 's/SELINUX=enforcing/SELINUX=disabled/' **/etc/selinux/config**

1. The -i (in-place) option is needed to replace the file (refer [here](https://www.grymoire.com/Unix/Sed.html#uh-62h)).
2. The selinux config file is in another location

I have tested on 2 different VM (Info shown below) and only the fix worked.

### VM Info 1
> **[root@ip-172-31-24-110 ~]#** rpm -q centos-release
> _centos-release-7-8.2003.0.el7.centos.x86_64_
> 
> **[root@ip-172-31-24-110 ~]#** hostnamectl
> _**Static hostname**: ip-172-31-24-110.ap-southeast-1.compute.internal
> **Icon name**: computer-vm
> **Chassis**: vm
> **Machine ID**: 5abe911a70f84ac4a6a7c8cdecec2b58
> **Boot ID:** b908dea4a13a423cb7246d1fba7d5e2a
> **Virtualization**: xen
> **Operating System**: CentOS Linux 7 (Core)
> **CPE OS Name**: cpe:/o:centos:centos:7
> **Kernel**: Linux 3.10.0-1127.19.1.el7.x86_64
> **Architecture**: x86-64_

### VM Info 2
> **[root@ip-172-31-24-110 ~]#** rpm -q centos-release
> _centos-release-7-7.1908.0.el7.centos.x86_64_
> 
> **[root@ip-172-31-24-110 ~]#** hostnamectl
> _**Static hostname**: ip-172-31-30-127.ap-southeast-1.compute.internal
> **Icon name**: computer-vm
> **Chassis**: vm
> **Machine ID:** 3d5c05376530a2eb49e3e90576f83c5b
> **Boot ID**: 5166b2da0f8844b2b65a4436283706a0
> **Virtualization**: xen
> **Operating System**: CentOS Linux 7 (Core)
> **CPE OS Name**: cpe:/o:centos:centos:7
> **Kernel**: Linux 3.10.0-1062.12.1.el7.x86_64
> **Architecture**: x86-64_

**Comment by nileshgovande** [comment]
Thanks @harrison-seow-seagate Pls submit a patch

**Comment by nileshgovande** [comment]
Merged changes, marking the issue fixed
