### ISSUE TITLE
CONTRIBUTING.md seems to be the old version

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-s3server#342]
https://github.com/Seagate/cortx-s3server/blob/main/CONTRIBUTING.md seems to be an older and inferior version of
https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md.

@nileshgovande , is this correct?

If so, @Saumya-Sunder , please move everything from the Quick Start Guide into the CONTRIBUTING.md file and then replace the contents of the Quick Start Guide with a message:
'This file has been moved to ***link to CONTRIBUTING.md***'

**Comment by nileshgovande** [comment]
Agree - @Saumya-Sunder  - pls do the needful

**Comment by yanqingfu** [comment]
1. need to update the https://github.com/Seagate/cortx/blob/main/CONTRIBUTING.md CORTX S3 link, seems not linking to the latest 
2. need to update the support link  (https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#reach-out-to-us) with https://github.com/Seagate/cortx/blob/main/SUPPORT.md

**Comment by nileshgovande** [comment]
@yanqingfu 
#1 - Pls check https://github.com/Seagate/cortx/pull/443 
#2 - Pls check - Pls check latest version - its already there
@johnbent  - https://github.com/Seagate/cortx-s3server/pull/350

**Comment by nileshgovande** [comment]
PR # 350 merged

**Comment by yanqingfu** [comment]
@nileshgovande

# 2 
![image](https://user-images.githubusercontent.com/68423216/97677431-32eddf80-1acd-11eb-96d1-a5678d25e0dd.png)

 https://github.com/Seagate/cortx/blob/main/SUPPORT.md seems better than **link in red** https://github.com/Seagate/cortx-s3server/blob/main/SUPPORT.md

**Comment by Saumya-Sunder** [comment]
Hey @yanqingfu, I will talk to John and update it. We added YouTube Channel link which is relevant to the CORTX repo. Let me discuss with him today and I will update accordingly.
