### ISSUE TITLE
Move authserver_notes.rst to s3 repo

### ISSUE THREAD

**Issue by nileshgovande** [Seagate/cortx-s3server#351]
Move https://github.com/Seagate/cortx/blob/main/doc/be/authserver_notes.rst to s3 rrepo and fix the outdated content

**Comment by Saumya-Sunder** [comment]
@nileshgovande as suggested I talked to both @sachitanands and @ypise but I haven't got the info on what exactly is outdated. Please suggest another SME name who can help me fix the outdated content in here.

**Comment by nileshgovande** [comment]
@Saumya-Sunder - Pls move the file as-is first to s3 repo and remove from cortx repo
We will take care of language/rewording later
But till then, let's keep this ticket open

**Comment by Saumya-Sunder** [comment]
Done @nileshgovande https://github.com/Seagate/cortx-s3server/pull/359

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

The ticket closed in GitHub

**Comment by cortx-admin** [comment]
> Mukul Malhotra commented in Jira Server:

Closed
