### ISSUE TITLE
aws s3 mb s3://seagatebucket make_bucket failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-s3server#356]
followed this guide https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md

` aws s3 mb s3://seagatebucket`
make_bucket failed: s3://seagatebucket SSL validation failed for https://s3.seagate.com/seagatebucket [SSL    : CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

**Comment by sachitanands** [comment]
Hi @yanqingfu we need to specify correct client certificate through aws config file
Please check if you have correct ca.crt path in **/root/.aws/config** as "**ca_bundle**"
Below is one sample where I have configured my ca.crt on my development vm.

[root@ssc-vm-0372 cortx-s3server]# cat ~/.aws/config
[default]
s3 =
    endpoint_url = https://s3.seagate.com
s3api =
    endpoint_url = https://s3.seagate.com
ca_bundle = /etc/ssl/stx-s3-clients/s3/ca.crt
[plugins]
endpoint = awscli_plugin_endpoint
[root@ssc-vm-0372 cortx-s3server]#

**Comment by yanqingfu** [comment]
@sachitanands apparently, we need to update the guidance as in the guide, there is no mention about ca_bundle.
![image](https://user-images.githubusercontent.com/68423216/97665526-9d475580-1ab6-11eb-8d58-a177a2a31cae.png)

**Comment by yanqingfu** [comment]
@sachitanands still has an error

> [root@ssc-vm-1061 cortx-s3server]# cat ~/.aws/config
> [default]
> output = text
> region = US
> s3 =
>      endpoint_url = https://s3.seagate.com
> s3api =
>      endpoint_url = https://s3.seagate.com
> ca_bundle = /etc/ssl/stx-s3-clients/s3/ca.crt
> [plugins]
> endpoint = awscli_plugin_endpoint

> [root@ssc-vm-1061 cortx-s3server]# aws s3 mb s3://seagatebucket
> make_bucket failed: s3://seagatebucket An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: The bucket you tried to create already exists, and you own it.

> [root@ssc-vm-1061 cortx-s3server]# aws s3 ls
> motr[29279]:  2a60  ERROR  [cas/service.c:1168:cas_fom_tick]  <! rc=-2
> motr[29271]:  3a60  ERROR  [cas/service.c:1168:cas_fom_tick]  <! rc=-2
> 2020-10-30 00:58:33 seagatebucket
> [root@ssc-vm-1061 cortx-s3server]# touch ./test_data
> [root@ssc-vm-1061 cortx-s3server]# aws s3 cp test_data s3://seagatebucket/
> motr[29279]:  9a60  ERROR  [cas/service.c:1168:cas_fom_tick]  <! rc=-2
> motr[29934]:  b980  ERROR  [cas/client.c:1167:cas_req_replied_ast]  <! rc=-2
> upload: ./test_data to s3://seagatebucket/test_data

**Comment by sachitanands** [comment]
Hi @yanqingfu 
BucketAlreadyOwnedByYou error shows bucket already exists.
in s3 bucket name should be unique hence we should either create new bucket with different name or delete existing bucket ( aws s3 rb s3://bucket-name --force) and then run this command again

Regarding ca_bundle.. 
Thanks for pointing out this documentation changes..
there are two ways we can run aws commands.
1) with SSL mode 
    - if you select this then endpoint entry should be "https://s3.seagate.com" and then only you need ca.bundle entry in config file.
2) without SSL mode
    - the document mentions this mode hence endpoint entry has "http://s3.seagate.com" and that's why we don't need ca_bundle path. 
I will work with our documentation team to update this info in our documentation

FYI @nileshgovande @Saumya-Sunder

**Comment by Saumya-Sunder** [comment]
@sachitanands will make the changes and tag you one the PR for Approval.

**Comment by nileshgovande** [comment]
Thanks a lot @sachitanands

**Comment by yanqingfu** [comment]
@sachitanands works now

> [root@ssc-vm-1061 cortx-s3server]# cat ~/.aws/config
> [default]
> output = text
> region = US
> s3 =
>      endpoint_url = https://s3.seagate.com
> s3api =
>      endpoint_url = https://s3.seagate.com
> ca_bundle = /etc/ssl/stx-s3-clients/s3/ca.crt
> [plugins]
> endpoint = awscli_plugin_endpoint
> [root@ssc-vm-1061 cortx-s3server]# aws s3 mb s3://seagatebucket
> make_bucket: seagatebucket
> [root@ssc-vm-1061 cortx-s3server]#

**Comment by yanqingfu** [comment]
@sachitanands but `aws s3 ls` has an error

[root@ssc-vm-1061 cortx-s3server]# aws s3 ls
motr[29279]:  2a60  ERROR  [cas/service.c:1168:cas_fom_tick]  <! rc=-2
motr[29271]:  3a60  ERROR  [cas/service.c:1168:cas_fom_tick]  <! rc=-2
2020-10-30 02:21:32 seagatebucket

**Comment by sachitanands** [comment]
Those are warnings.. please ignore them.

**Comment by yanqingfu** [comment]
@sachitanands thanks

**Comment by Saumya-Sunder** [comment]
Updated the doc here https://github.com/Seagate/cortx-s3server/pull/362
