### ISSUE TITLE
Pls add supported iam api calls

### ISSUE THREAD

**Issue by gregnsk** [Seagate/cortx-s3server#366]
We need to add supported IAM api calls to https://github.com/Seagate/cortx-s3server/blob/main/docs/s3-supported-api.md

**Comment by bkirunge7** [comment]
@gregnsk  this capture  IAM as well api please check section S3 IAM APIs  https://github.com/Seagate/cortx-s3server/blob/main/docs/s3-supported-api.md

**Comment by gregnsk** [comment]
Could you add a link to s3iamcli download?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bkirunge7** [comment]
http://cortx-storage.colo.seagate.com/releases/cortx/github/main/centos-7.8.2003/s3server_last_successful/
cortx-s3iamcli-1.0.0-14_git2c258f87.noarch.rpm 

We can also use aws iam cli 
https://docs.aws.amazon.com/cli/latest/reference/iam/

**Comment by gregnsk** [comment]
it's better to use aws iam cli in the external documentation - it's better known

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gregnsk** [comment]
actually, the page is called API reference. Please list supported API calls with the expected parameters, etc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bkirunge7** [comment]
@gregnsk  Created this https://jts.seagate.com/browse/EOS-15124 to track IAM API document updated
