### ISSUE TITLE
 requests.exceptions.HTTPError: 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-s3server#621]
I was following along with the steps in the Quick Start Guide and when I run the command ./init.sh -a I am prompted for a GitHub Access Token which I created following this guide: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token once I enter this token I get this error: requests.exceptions.HTTPError: 403 Client Error: Forbidden

**Comment by Saumya-Sunder** [comment]
@hessio, looks like there is an issue with your API. Could you please check and let me know if the S3 API is running fine?

**Comment by hessio** [comment]
I am not sure how to check this?

**Comment by Saumya-Sunder** [comment]
@hessio Are you testing this on a local VM or a cloud VM?

**Comment by hessio** [comment]
local VM

**Comment by nileshgovande** [comment]
Looks like issue is resolved since @hessio seems to work further. Closing
