### ISSUE TITLE
Syntax Error during ./init.sh

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-s3server#786]
Did some changes cause this error, I did not encounter this previously.
Initially I thought I entered my PAT incorrectly and I even generated a new one but it doesn't seem like that's the issue.

```
Git Access Token: ***
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==21.0.1', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip-21.0.1-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Script**
```
sudo su -

yum install -y git
yum install -y ansible
yum install -y python3
yum install -y python-pip
yum install -y epel-release

setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

# ============= REBOOT VM =============

sudo su -

git clone --recursive https://github.com/Seagate/cortx-s3server.git -b main
cd cortx-s3server
git submodule update --init --recursive && git status

cd ./scripts/env/dev
./init.sh -a
# ============= ENTER GitHub PAT =============
```

CentOS Version `3.10.0-1062.el7.x86_64`
Using Oracle VM VirtualBox & VMWare WorkStation 16 Player

**Comment by johnbent** [comment]
Hi @harrison-seow-seagate , I think what's happening is that you're using python 2.7 but you should be using python 3.6 or greater.  Can you try again with python3.6 and see if that fixes your problem please?

**Comment by harrison-seow-seagate** [comment]
Hi @johnbent, thanks for the suggestion, I never thought it could be a Python version issue, as it never occurred previously (based on this [issue](https://github.com/Seagate/cortx-motr/issues/217)). *Also reproduced the same issue on AWS (previously did not occur).

Apparently if I switch to Python 3 using `alias python='/usr/bin/python3.6'` I would still encounter Syntax Error, but if I switch the Python version system wide using `update-alternatives --config python`, yum starts to stop working, and many other packages that depends on the fact that python = python2.7 (referred from [link](https://unix.stackexchange.com/questions/524552/upgraded-python-and-now-i-cant-run-yum-upgrade)).

I'm not sure if this is caused by new packages installed from yum or recent code changes. Or maybe I'm wrong and is missing something along the way.

**Comment by sachitanands** [comment]
Hi @harrison-seow-seagate issue seems to be with pip version hence you are seeing errors on seagate s3 as well as aws.
from the call stack, you are using pip version 21.0.1 which is latest one.. so could you please try downgrade it to 20.0.3 ?
pls check if this works or not :  pip install pip==20.3.3

please refer this issue as well issue : https://github.com/pypa/pip/issues/9500

**Comment by harrison-seow-seagate** [comment]
Hi @sachitanands, thanks for the suggestion, I retried the setup on AWS and I got it working.
I was wondering if `yum install` should specify a specific version instead, if this is the issue?

**Script for reference**
```
sudo su -

yum install -y git
yum install -y ansible
yum install -y python3
yum install -y python-pip
yum install -y epel-release
yum install wget -y
wget https://buildlogs.centos.org/c7.1908.00.x86_64/kernel/20190808101829/3.10.0-1062.el7.x86_64/kernel-devel-3.10.0-1062.el7.x86_64.rpm
yum install kernel-devel-3.10.0-1062.el7.x86_64.rpm -y

pip install pip==20.3.3

setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

git clone --recursive https://github.com/Seagate/cortx-s3server.git -b main
cd cortx-s3server
git submodule update --init --recursive && git status

cd ./scripts/env/dev
./init.sh -a
```

**Comment by nileshgovande** [comment]
@Saumya-Sunder - Pls update to use  'pip install pip==20.3.3'

**Comment by nileshgovande** [comment]
@mukul-seagate11 - Pls assign the issue to @Saumya-Sunder  - it seems that I cannot reassign the issue.

**Comment by johnbent** [comment]
@Saumya-Sunder , can you please confirm that you're handling this?

**Comment by Saumya-Sunder** [comment]
Hi @johnbent, doing it right away!

**Comment by Saumya-Sunder** [comment]
Done here https://github.com/Seagate/cortx-s3server/pull/801. @nileshgovande please approve. @mukul-seagate11 I am unable to close my tickets. Kindly close this, I will tag you once my PR gets approved.

**Comment by harrison-seow-seagate** [comment]
Problem has been resolved, PR has been raised, I will close this issue then.
Thanks everyone.
