### ISSUE TITLE
Sanity Test fails with missing access key argument

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-s3server#794]
The sanity test `sh /opt/seagate/cortx/s3/scripts/s3-sanity-test.sh` in the Cortx on OVA [guide](https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst) Numbering 13, fails if no S3 account has been created. The script fails with the following error:

**Error Snippet**
```
...
s3iamcli: error: argument --access_key: expected one argument
Failed
```
According to the instructions, S3 account will not be created until Numbering 15, asking you to create an S3 account in the Testing IO [guide](https://github.com/Seagate/cortx/blob/main/doc/testing_io.rst).

Should an S3 account be created **before** running the sanity test? If so, perhaps the sanity test should be numbered **after** an S3 account is created.

_Found this issue when testing on Oracle VM VirtualBox._

**Comment by mukul-seagate11** [comment]
@harrison-seow-seagate, This bug is already reported to the maintainers & will be fixed in next OVA release i.e. OVA 1.0.3

**Comment by harrison-seow-seagate** [comment]
@mukul-seagate11, I see. I think this issue is also opened on the wrong project, should I keep it open until the release of OVA 1.0.3? _Since I don't see any open issue on this._

**Comment by mukul-seagate11** [comment]
@harrison-seow-seagate, Sure and you will get notified once OVA 1.0.3 is released

**Comment by harrison-seow-seagate** [comment]
I saw that the release of [cortx-va-1.0.3.ova](https://github.com/Seagate/cortx/releases/download/ova-1.0.3/cortx-va-1.0.3.ova) is available and there's a significant drop in size (Awesome).

I have tested the sanity-test.sh with the new ova release and it worked, will be closing this issue as resolved.
Thank you.
