### ISSUE TITLE
Potentially dangerous construction

### ISSUE THREAD

**Issue by just-now** [Seagate/cortx-s3server#812]
If `object_metadata->get_layout_id()` returns 0, then during `first_byte_offset_block` calculation division by zero can be seen.

I've seen it a few times during UT development.

```
void S3GetObjectAction::set_total_blocks_to_read_from_object() {
...
  } else {
...
    size_t motr_unit_size =
        S3MotrLayoutMap::get_instance()->get_unit_size_for_layout(
            object_metadata->get_layout_id());
    size_t first_byte_offset_block =
        (first_byte_offset_to_read + motr_unit_size) / motr_unit_size;
```

**Comment by nileshgovande** [comment]
Thanks @just-now 
motr unit size cannot be zero since t represents a unit of data transferred to/from motr in one iteration

**Comment by justinzw** [comment]
@just-now  - > Just wondering what the fix for this might be? 

Do you need to just check for 0 and throw an exception?

If so- could this possibly be a community contribuition?

**Comment by nileshgovande** [comment]
No response from @just-now  - Closing
