### ISSUE TITLE
init.sh script references internal .rpm file

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx-s3server#822]
In the quickstart guide: https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md you need to run `init.sh` but it references an internal .rpm file that is not accessbile outside the Seagate network.

https://github.com/Seagate/cortx-s3server/blob/e27b1b0d4ce4fbe3b4103bb150fbb9a525729b77/scripts/env/dev/init.sh#L220

This means if you run the guide outside of the network it will fail at this point

**Comment by justinzw** [comment]
Can we possible host this .rpm in the github repo or release folder?

**Comment by sachitanands** [comment]
Hi @justinzw , one correction here,
1) for opensource , we need to run **init.sh -a**  . please note -a is for opensource parameter which will download all the build dependencies required for cortx and it will be used as local repo.
2) regarding isa-l-2.30.0-1.el7.x86_64.rpm , this rpm is already available in build dependencies ([build_dependencies_list](https://github.com/Seagate/cortx/releases/tag/build-dependencies)) of cortx in case of opensource community.
3) The line you mentioned here will be called only in case of internal seagate developer .
Hence it will work for both internal and external contributors.

**Comment by johnbent** [comment]
Sachitanand,

Thanks for sharing this info. However, why do we have a separate build for internal and external. If it is possible for it to build externally, then why do our internal devs use a separate build path?  We should optimize and be efficient and all share just the single external build.

Or can you help me understand why we need separate please?

Thanks

________________________________

**Comment by nileshgovande** [comment]
@johnbent - this happened historically when the open-source transition was in progress - we have ended up adding a separate switch for open source.
In theory - we can and should remove the '-a' switch but it needs more exploration.

**Comment by nileshgovande** [comment]
No work needed as of now.
