### ISSUE TITLE
Add more performance, robustness and usability to s3_log()

### ISSUE THREAD

**Issue by just-now** [Seagate/cortx-s3server#833]
Currently, s3_log() allocates a buffer for every call which has quite unpleasant implications in cases of memory pressure and performance impacts in other cases.

It's proposed to replace asprintf with sNprintf, replace allocation with thread local buffers, as a bonus update semantics of s3_iem() so that it becomes similar to s3 log. Add constexperssions support to s3_log, example: s3_log(cond ? S3_LOG_DEBUG : S3_LOG_ERROR, ...).
https://github.com/Seagate/cortx-s3server/pull/831

**Comment by nileshgovande** [comment]
@vimalraghwani20 - Pls mark this as closed when done.

**Comment by nileshgovande** [comment]
PR merged
