### ISSUE TITLE
./jenkins-build.sh command fails with FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-s3server#873]
When I run ./jenkins-build.sh command completes but finishes with `FAILED: Build did NOT complete successfully`  
  
Attached here is the error output of the command:  
`INFO: Analysed target //:s3ut (9 packages loaded).`  
`INFO: Found 1 target...`  
`ERROR: /root/cortx-s3server/BUILD:78:1: C++ compilation of rule '//:s3ut' failed (Exit 4)`  
`gcc: internal compiler error: Killed (program cc1plus)`  
`Please submit a full bug report,`  
`with preprocessed source if appropriate.`  
`See <http://bugzilla.redhat.com/bugzilla> for instructions.`  
`Target //:s3ut failed to build`  
`Use --verbose_failures to see the command lines of failed build steps.`  
`INFO: Elapsed time: 279.139s, Critical Path: 273.77s`  
`INFO: 11 processes, local.`  
`FAILED: Build did NOT complete successfully`

**Comment by sachitanands** [comment]
this issue occurs usually when we have less RAM ..and while building s3server we consume all available RAM which results into process failure.
I had a discussion with @hessio and we saw vm hsa only 2GB of RAM. 
@hessio  will create new vm with bigger RAM and disk space to avoid these issues.
Hence closing this issue.
